import { protectedProcedure } from "../../../create-context";
import { prisma } from "@/backend/lib/prisma";

export const seedTestDataProcedure = protectedProcedure.mutation(
  async ({ ctx }) => {
    console.log("🌱 Seeding comprehensive test data...");

    const userId = ctx.user.id;

    const org1 = await prisma.organization.create({
      data: {
        name: "TechEvents Global",
        slug: "techevents-global",
        description: "Líder mundial en conferencias de tecnología y eventos de innovación digital",
        logoUrl: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200",
        coverUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200",
        website: "https://techevents.global",
        contactEmail: "info@techevents.global",
        contactPhone: "+52 55 1234 5678",
      },
    });

    const org2 = await prisma.organization.create({
      data: {
        name: "Live Music Productions",
        slug: "live-music-pro",
        description: "Organizadores de los mejores festivales y conciertos de México",
        logoUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=200",
        coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200",
        website: "https://livemusicpro.mx",
        contactEmail: "contacto@livemusicpro.mx",
        contactPhone: "+52 55 8765 4321",
      },
    });

    const org3 = await prisma.organization.create({
      data: {
        name: "Elite Business Events",
        slug: "elite-business",
        description: "Eventos corporativos de alto nivel y networking empresarial exclusivo",
        logoUrl: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200",
        coverUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200",
        website: "https://elitebusiness.mx",
        contactEmail: "eventos@elitebusiness.mx",
        contactPhone: "+52 55 9988 7766",
      },
    });

    const org4 = await prisma.organization.create({
      data: {
        name: "Deportes Extremos MX",
        slug: "deportes-extremos",
        description: "Organizadores de competencias y eventos de deportes extremos",
        logoUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=200",
        coverUrl: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=1200",
        website: "https://deportesextremosmx.com",
        contactEmail: "info@deportesextremosmx.com",
        contactPhone: "+52 55 5544 3322",
      },
    });

    const event1 = await prisma.event.create({
      data: {
        name: "Conferencia de Tecnología 2025",
        description: "La conferencia más importante de tecnología del año. Expositores internacionales, talleres prácticos y networking con los mejores del sector.",
        date: new Date("2025-06-15T09:00:00Z"),
        time: "09:00 AM",
        venueName: "Centro de Convenciones CDMX",
        location: "Av. Paseo de la Reforma 476, Cuauhtémoc, CDMX",
        imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
        organizerLogoUrl: org1.logoUrl,
        venuePlanUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800",
        employeeNumberLabel: "Número de Empleado",
        successSoundId: "success-1",
        errorSoundId: "error-1",
        vibrationEnabled: true,
        vibrationIntensity: "heavy",
        primaryColor: "#2563eb",
        secondaryColor: "#3b82f6",
        accentColor: "#60a5fa",
        createdBy: userId,
        organizationId: org1.id,
      },
    });

    const event2 = await prisma.event.create({
      data: {
        name: "Festival de Música Verano 2025",
        description: "El festival más esperado del año con artistas nacionales e internacionales. Tres días de música, arte y cultura.",
        date: new Date("2025-07-20T16:00:00Z"),
        time: "04:00 PM",
        venueName: "Foro Sol",
        location: "Viaducto Río de la Piedad s/n, Granjas México, CDMX",
        imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800",
        organizerLogoUrl: org2.logoUrl,
        venuePlanUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800",
        employeeNumberLabel: "ID de Acceso",
        successSoundId: "success-2",
        errorSoundId: "error-1",
        vibrationEnabled: true,
        vibrationIntensity: "medium",
        primaryColor: "#dc2626",
        secondaryColor: "#ef4444",
        accentColor: "#f87171",
        createdBy: userId,
        organizationId: org2.id,
      },
    });

    const event3 = await prisma.event.create({
      data: {
        name: "Gala Anual de Negocios",
        description: "Evento exclusivo de networking empresarial. Cena de gala, premios a la excelencia empresarial y presentación de nuevos proyectos.",
        date: new Date("2025-08-10T19:00:00Z"),
        time: "07:00 PM",
        venueName: "Hotel Four Seasons",
        location: "Paseo de la Reforma 500, Juárez, CDMX",
        imageUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800",
        organizerLogoUrl: org3.logoUrl,
        venuePlanUrl: "https://images.unsplash.com/photo-1519167758481-83f29da8a803?w=800",
        employeeNumberLabel: "Código de Invitación",
        successSoundId: "success-1",
        errorSoundId: "error-2",
        vibrationEnabled: false,
        vibrationIntensity: "light",
        primaryColor: "#7c3aed",
        secondaryColor: "#8b5cf6",
        accentColor: "#a78bfa",
        createdBy: userId,
        organizationId: org3.id,
      },
    });

    const event4 = await prisma.event.create({
      data: {
        name: "Hackathon Innovation 2025",
        description: "48 horas de código intensivo. Desarrolladores de todo el país compitiendo por premios de más de $500,000 MXN.",
        date: new Date("2025-09-05T18:00:00Z"),
        time: "06:00 PM",
        venueName: "Campus Tecnológico",
        location: "Av. Universidad 3000, Copilco Universidad, CDMX",
        imageUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
        organizerLogoUrl: org1.logoUrl,
        venuePlanUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        employeeNumberLabel: "Código de Equipo",
        successSoundId: "success-1",
        errorSoundId: "error-1",
        vibrationEnabled: true,
        vibrationIntensity: "heavy",
        primaryColor: "#059669",
        secondaryColor: "#10b981",
        accentColor: "#34d399",
        createdBy: userId,
        organizationId: org1.id,
      },
    });

    const event5 = await prisma.event.create({
      data: {
        name: "Rock en Español Festival",
        description: "Las mejores bandas de rock en español en un solo lugar. Una noche épica de rock y energía.",
        date: new Date("2025-10-12T19:00:00Z"),
        time: "07:00 PM",
        venueName: "Palacio de los Deportes",
        location: "Añil 635, Granjas México, Iztacalco, CDMX",
        imageUrl: "https://images.unsplash.com/photo-1501612780327-45045538702b?w=800",
        organizerLogoUrl: org2.logoUrl,
        venuePlanUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800",
        employeeNumberLabel: "Pulsera ID",
        successSoundId: "success-2",
        errorSoundId: "error-1",
        vibrationEnabled: true,
        vibrationIntensity: "heavy",
        primaryColor: "#ea580c",
        secondaryColor: "#f97316",
        accentColor: "#fb923c",
        createdBy: userId,
        organizationId: org2.id,
      },
    });

    const event6 = await prisma.event.create({
      data: {
        name: "Cumbre de Liderazgo Empresarial",
        description: "Los CEOs más influyentes de México comparten sus estrategias de éxito. Networking exclusivo y casos de estudio.",
        date: new Date("2025-11-20T08:00:00Z"),
        time: "08:00 AM",
        venueName: "World Trade Center México",
        location: "Montecito 38, Nápoles, Benito Juárez, CDMX",
        imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800",
        organizerLogoUrl: org3.logoUrl,
        venuePlanUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
        employeeNumberLabel: "Badge ID",
        successSoundId: "success-1",
        errorSoundId: "error-2",
        vibrationEnabled: false,
        vibrationIntensity: "light",
        primaryColor: "#0891b2",
        secondaryColor: "#06b6d4",
        accentColor: "#22d3ee",
        createdBy: userId,
        organizationId: org3.id,
      },
    });

    const event7 = await prisma.event.create({
      data: {
        name: "Campeonato Nacional de BMX",
        description: "Los mejores riders de BMX de México compiten por el título nacional. Acrobacias, velocidad y adrenalina pura.",
        date: new Date("2025-07-28T10:00:00Z"),
        time: "10:00 AM",
        venueName: "Parque Extremo Del Valle",
        location: "Av. División del Norte 3000, Del Valle, CDMX",
        imageUrl: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800",
        organizerLogoUrl: org4.logoUrl,
        venuePlanUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800",
        employeeNumberLabel: "Número de Competidor",
        successSoundId: "success-1",
        errorSoundId: "error-1",
        vibrationEnabled: true,
        vibrationIntensity: "heavy",
        primaryColor: "#eab308",
        secondaryColor: "#facc15",
        accentColor: "#fde047",
        createdBy: userId,
        organizationId: org4.id,
      },
    });

    const event8 = await prisma.event.create({
      data: {
        name: "Festival Electrónico Sunrise",
        description: "Los mejores DJs internacionales en una experiencia musical única. Arte visual, luces y la mejor música electrónica.",
        date: new Date("2025-12-31T22:00:00Z"),
        time: "10:00 PM",
        venueName: "Autódromo Hermanos Rodríguez",
        location: "Granjas México, Iztacalco, CDMX",
        imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800",
        organizerLogoUrl: org2.logoUrl,
        venuePlanUrl: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800",
        employeeNumberLabel: "Wristband ID",
        successSoundId: "success-2",
        errorSoundId: "error-1",
        vibrationEnabled: true,
        vibrationIntensity: "medium",
        primaryColor: "#8b5cf6",
        secondaryColor: "#a78bfa",
        accentColor: "#c4b5fd",
        createdBy: userId,
        organizationId: org2.id,
      },
    });

    const pool1 = await prisma.capacityPool.create({
      data: {
        eventId: event1.id,
        name: "Pool General Conferencia",
        totalCapacity: 500,
        usedCapacity: 0,
      },
    });

    const pool2 = await prisma.capacityPool.create({
      data: {
        eventId: event2.id,
        name: "Pool General Festival",
        totalCapacity: 1000,
        usedCapacity: 0,
      },
    });

    const pool4 = await prisma.capacityPool.create({
      data: {
        eventId: event4.id,
        name: "Pool Hackathon",
        totalCapacity: 300,
        usedCapacity: 0,
      },
    });

    const pool5 = await prisma.capacityPool.create({
      data: {
        eventId: event5.id,
        name: "Pool Rock Festival",
        totalCapacity: 2000,
        usedCapacity: 0,
      },
    });

    await prisma.ticket.createMany({
      data: [
        {
          eventId: event1.id,
          name: "Entrada General",
          description: "Acceso completo a todas las conferencias y talleres",
          imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400",
          price: 1500,
          currency: "MXN",
          capacityType: "shared",
          sharedCapacityPoolId: pool1.id,
          saleStartDate: new Date("2025-01-01"),
          saleEndDate: new Date("2025-06-14"),
          isActive: true,
          formFields: JSON.stringify([
            { label: "Nombre Completo", type: "text", required: true },
            { label: "Empresa", type: "text", required: false },
          ]),
        },
        {
          eventId: event1.id,
          name: "VIP Pass",
          description: "Acceso VIP con meet & greet exclusivo",
          imageUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=400",
          price: 3500,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 50,
          saleStartDate: new Date("2025-01-01"),
          saleEndDate: new Date("2025-06-14"),
          isActive: true,
        },
        {
          eventId: event2.id,
          name: "Entrada General Festival",
          description: "Acceso a las tres noches del festival",
          imageUrl: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=400",
          price: 2000,
          currency: "MXN",
          capacityType: "shared",
          sharedCapacityPoolId: pool2.id,
          saleStartDate: new Date("2025-02-01"),
          saleEndDate: new Date("2025-07-19"),
          isActive: true,
        },
        {
          eventId: event2.id,
          name: "Pase Backstage",
          description: "Acceso backstage y meet & greet con artistas",
          imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400",
          price: 5000,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 100,
          saleStartDate: new Date("2025-02-01"),
          saleEndDate: new Date("2025-07-19"),
          isActive: true,
        },
        {
          eventId: event3.id,
          name: "Mesa Individual",
          description: "Reserva de mesa individual para la gala",
          imageUrl: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=400",
          price: 5000,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 50,
          saleStartDate: new Date("2025-03-01"),
          saleEndDate: new Date("2025-08-09"),
          isActive: true,
        },
        {
          eventId: event3.id,
          name: "Mesa Empresarial (10 personas)",
          description: "Mesa empresarial con capacidad para 10 personas",
          imageUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=400",
          price: 45000,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 10,
          saleStartDate: new Date("2025-03-01"),
          saleEndDate: new Date("2025-08-09"),
          isActive: true,
        },
        {
          eventId: event4.id,
          name: "Registro Individual",
          description: "Registro individual para participar en el hackathon",
          imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=400",
          price: 500,
          currency: "MXN",
          capacityType: "shared",
          sharedCapacityPoolId: pool4.id,
          saleStartDate: new Date("2025-01-01"),
          saleEndDate: new Date("2025-09-04"),
          isActive: true,
        },
        {
          eventId: event4.id,
          name: "Equipo Completo (4 personas)",
          description: "Registro de equipo completo con workspace dedicado",
          imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400",
          price: 1800,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 75,
          saleStartDate: new Date("2025-01-01"),
          saleEndDate: new Date("2025-09-04"),
          isActive: true,
        },
        {
          eventId: event5.id,
          name: "General Admission",
          description: "Entrada general al festival",
          imageUrl: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400",
          price: 1200,
          currency: "MXN",
          capacityType: "shared",
          sharedCapacityPoolId: pool5.id,
          saleStartDate: new Date("2025-03-01"),
          saleEndDate: new Date("2025-10-11"),
          isActive: true,
        },
        {
          eventId: event5.id,
          name: "VIP Golden Circle",
          description: "Zona preferente cerca del escenario",
          imageUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400",
          price: 3500,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 200,
          saleStartDate: new Date("2025-03-01"),
          saleEndDate: new Date("2025-10-11"),
          isActive: true,
        },
        {
          eventId: event6.id,
          name: "Entrada Individual",
          description: "Acceso individual a la cumbre",
          imageUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=400",
          price: 8000,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 100,
          saleStartDate: new Date("2025-04-01"),
          saleEndDate: new Date("2025-11-19"),
          isActive: true,
        },
        {
          eventId: event7.id,
          name: "Entrada Espectador",
          description: "Acceso para ver las competencias",
          imageUrl: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=400",
          price: 300,
          currency: "MXN",
          capacityType: "unlimited",
          saleStartDate: new Date("2025-02-01"),
          saleEndDate: new Date("2025-07-27"),
          isActive: true,
        },
        {
          eventId: event7.id,
          name: "Registro Competidor",
          description: "Registro oficial para competidores",
          imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
          price: 1500,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 50,
          saleStartDate: new Date("2025-02-01"),
          saleEndDate: new Date("2025-07-20"),
          isActive: true,
        },
        {
          eventId: event8.id,
          name: "Early Bird",
          description: "Precio especial de preventa",
          imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400",
          price: 1800,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 500,
          saleStartDate: new Date("2025-05-01"),
          saleEndDate: new Date("2025-09-01"),
          isActive: true,
        },
        {
          eventId: event8.id,
          name: "VIP Experience",
          description: "Acceso VIP con área exclusiva y bebidas premium",
          imageUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=400",
          price: 5500,
          currency: "MXN",
          capacityType: "dedicated",
          dedicatedCapacity: 150,
          saleStartDate: new Date("2025-05-01"),
          saleEndDate: new Date("2025-12-30"),
          isActive: true,
        },
      ],
    });

    await prisma.attendee.createMany({
      data: [
        {
          eventId: event1.id,
          fullName: "Juan Pérez García",
          email: "juan.perez@empresa.com",
          employeeNumber: "EMP001",
          ticketCode: "TECH2025-001",
        },
        {
          eventId: event1.id,
          fullName: "María González López",
          email: "maria.gonzalez@empresa.com",
          employeeNumber: "EMP002",
          ticketCode: "TECH2025-002",
          checkedIn: true,
          checkedInAt: new Date(),
        },
        {
          eventId: event1.id,
          fullName: "Carlos Rodríguez Martínez",
          email: "carlos.rodriguez@empresa.com",
          employeeNumber: "EMP003",
          ticketCode: "TECH2025-003",
        },
        {
          eventId: event2.id,
          fullName: "Ana María Fernández",
          email: "ana.fernandez@email.com",
          employeeNumber: "FAN001",
          ticketCode: "FEST2025-001",
        },
        {
          eventId: event2.id,
          fullName: "Roberto Silva Torres",
          email: "roberto.silva@email.com",
          employeeNumber: "FAN002",
          ticketCode: "FEST2025-002",
          checkedIn: true,
          checkedInAt: new Date(),
        },
        {
          eventId: event3.id,
          fullName: "Patricia Ramírez Sánchez",
          email: "patricia.ramirez@corporativo.com",
          employeeNumber: "CORP001",
          ticketCode: "GALA2025-001",
        },
        {
          eventId: event4.id,
          fullName: "Diego Torres",
          email: "diego@dev.com",
          employeeNumber: "HACK001",
          ticketCode: "HACK2025-001",
        },
        {
          eventId: event4.id,
          fullName: "Sofía Méndez",
          email: "sofia@dev.com",
          employeeNumber: "HACK002",
          ticketCode: "HACK2025-002",
          checkedIn: true,
          checkedInAt: new Date(),
        },
        {
          eventId: event5.id,
          fullName: "Luis Ramírez",
          email: "luis@rock.com",
          employeeNumber: "ROCK001",
          ticketCode: "ROCK2025-001",
        },
        {
          eventId: event5.id,
          fullName: "Carmen Vega",
          email: "carmen@rock.com",
          employeeNumber: "ROCK002",
          ticketCode: "ROCK2025-002",
        },
        {
          eventId: event6.id,
          fullName: "Roberto Sánchez",
          email: "roberto@empresa.com",
          employeeNumber: "CEO001",
          ticketCode: "LEAD2025-001",
          checkedIn: true,
          checkedInAt: new Date(),
        },
        {
          eventId: event7.id,
          fullName: "Alejandro Cruz",
          email: "alex@bmx.com",
          employeeNumber: "BMX001",
          ticketCode: "BMX2025-001",
        },
        {
          eventId: event8.id,
          fullName: "Valeria Morales",
          email: "vale@music.com",
          employeeNumber: "EDM001",
          ticketCode: "SUNRISE2025-001",
        },
        {
          eventId: event8.id,
          fullName: "Fernando López",
          email: "fer@music.com",
          employeeNumber: "EDM002",
          ticketCode: "SUNRISE2025-002",
          checkedIn: true,
          checkedInAt: new Date(),
        },
      ],
    });

    await prisma.prize.createMany({
      data: [
        {
          eventId: event1.id,
          name: "MacBook Pro 16 pulgadas",
          description: "La última generación de MacBook Pro con chip M3 Max",
          imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
          quantity: 1,
        },
        {
          eventId: event1.id,
          name: "iPad Air",
          description: "iPad Air de última generación con Apple Pencil incluido",
          imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
          quantity: 2,
        },
        {
          eventId: event1.id,
          name: "Curso Online de Programación",
          description: "Acceso completo a plataforma de cursos por 1 año",
          imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400",
          quantity: 5,
        },
        {
          eventId: event2.id,
          name: "Meet & Greet con Artista Principal",
          description: "Encuentro exclusivo con el artista principal del festival",
          imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400",
          quantity: 1,
        },
        {
          eventId: event2.id,
          name: "Pase VIP para próximo festival",
          description: "Acceso VIP completo para el festival del próximo año",
          imageUrl: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400",
          quantity: 3,
        },
        {
          eventId: event3.id,
          name: "Viaje para 2 personas a Cancún",
          description: "Viaje todo incluido a Cancún por 5 días y 4 noches",
          imageUrl: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400",
          quantity: 1,
        },
        {
          eventId: event4.id,
          name: "Premio al Mejor Proyecto",
          description: "$250,000 MXN + Mentoría con inversores",
          imageUrl: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400",
          quantity: 1,
        },
        {
          eventId: event4.id,
          name: "Premio Innovación Social",
          description: "$100,000 MXN + Incubación por 6 meses",
          imageUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400",
          quantity: 1,
        },
        {
          eventId: event5.id,
          name: "Guitarra Fender Stratocaster Firmada",
          description: "Firmada por todos los artistas del festival",
          imageUrl: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400",
          quantity: 1,
        },
        {
          eventId: event5.id,
          name: "Pases Backstage",
          description: "Acceso backstage y meet & greet",
          imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400",
          quantity: 5,
        },
        {
          eventId: event7.id,
          name: "Bicicleta BMX Profesional",
          description: "BMX de competición profesional completa",
          imageUrl: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=400",
          quantity: 1,
        },
        {
          eventId: event8.id,
          name: "Pase VIP Anual",
          description: "Acceso VIP a todos los festivales del año",
          imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400",
          quantity: 2,
        },
      ],
    });

    console.log("✅ Comprehensive test data seeded successfully");
    console.log(`📊 Created 4 organizations`);
    console.log(`🎉 Created 8 events with tickets, attendees, and prizes`);
    console.log(`\n🏪 Stores created:`);
    console.log(`   - /store/techevents-global (TechEvents Global - 3 eventos)`);
    console.log(`   - /store/live-music-pro (Live Music Productions - 3 eventos)`);
    console.log(`   - /store/elite-business (Elite Business Events - 2 eventos)`);
    console.log(`   - /store/deportes-extremos (Deportes Extremos MX - 1 evento)`);

    return {
      success: true,
      organizations: [org1, org2, org3, org4],
      events: [event1, event2, event3, event4, event5, event6, event7, event8],
    };
  }
);
